name: Build PWA
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup Node
        uses: actions/setup-node@v2
        with:
          node-version: '18'
      - name: Install dependencies
        run: |
          npm install
          npx expo install react-native-web react-dom @expo/metro-runtime
      - name: Build PWA
        run: npx expo export --platform web
      - name: Upload PWA
        uses: actions/upload-artifact@v4
        with:
          name: pwa-files
          path: dist/
